title: Hi there, welcome to my Github! ğŸ‘‹ğŸ¼
tagline: IT Blog by Elbar Israilov Software Engineer Mobile Developer Android Developer
author: Elbar Israilov
github_username:  Elbar

theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-menus
