title: Hi there! ğŸ‘‹ğŸ¼ Welcome to my page! 
tagline: Elbar Israilov Software Engineer Mobile Developer Android Developer
author: Elbar Israilov
github_username:  Elbar

theme: jekyll-theme-tactile
plugins:
  - jekyll-feed
  - jekyll-menus
