title: IT Blog by Elbar Israilov
tagline: IT Blog by Elbar Israilov Software Engineer Mobile Developer Android Developer
author: Elbar Israilov
github_username:  Elbar

theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-menus
