title: Hi there! ğŸ‘‹ğŸ¼
tagline: Elbar Israilov Software Engineer Mobile Developer Android Developer
author: Elbar Israilov
github_username:  Elbar

theme: jekyll-theme-architect
plugins:
  - jekyll-feed
  - jekyll-menus
