title: Hi, my name is Elbar Israilov ğŸ‘‹ğŸ¼
tagline: Elbar Israilov Software Engineer Mobile Developer Android Developer
author: Elbar Israilov
github_username:  Elbar

theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-menus
